services:
  - type: web
    name: twilio-elevenlabs-relay
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: AGENT_ID
        sync: false
      - key: TRANSCRIPT_LOGGING
        value: "true"
    autoDeploy: true
    region: oregon
